---
lib_name: lib_locks
project: '{{lib_name}}'
title: '{{lib_name}}: Lock handling library'
version: 2.3.0

documentation:
  exclude_patterns_path: doc/exclude_patterns.inc
  substitutions_path: doc/substitutions.inc
  root_doc: doc/rst/locks.rst
  linkcheck_ignore_regex: ['']
  cognidox_part_number: XM-006390-UG
  doxygen_projects:
    lib_locks:
      doxyfile_path: doc/Doxyfile.inc
  pdfs:
    doc/rst/locks.rst:
      pdf_title: '{{title}}'
      pdf_filename: '{{lib_name}}_v{{version}}'
    README.rst:
      pdf_title: '{{title}} (README)'
      pdf_filename: '{{lib_name}}_v{{version}}_readme'
      pdf_short: yes
software:
  cognidox_part_number: XM-007510-SM
